const suggestions = [
  {
    id: 1,
    foodName: "Yam and Egg Sauce",
    foodProcedure:
      "Boiled yam served with scrambled eggs, tomatoes, onions, and peppers",
    caloriesContained: 450,
    timeTaken: 25,
    takenAs: "Breakfast",
  },
  {
    id: 2,
    foodName: "Jollof Rice with Chicken",
    foodProcedure:
      "Spicy tomato-based rice cooked with peppers, onions, and served with grilled chicken",
    caloriesContained: 600,
    timeTaken: 50,
    takenAs: "Lunch",
  },
  {
    id: 3,
    foodName: "Egusi Soup with Pounded Yam",
    foodProcedure:
      "Melon seed soup with vegetables, meat, and fish, served with pounded yam",
    caloriesContained: 700,
    timeTaken: 60,
    takenAs: "Dinner",
  },
  {
    id: 4,
    foodName: "Akara and Pap (Ogi)",
    foodProcedure: "Fried bean cakes served with fermented corn pudding (pap)",
    caloriesContained: 380,
    timeTaken: 30,
    takenAs: "Breakfast",
  },
  {
    id: 5,
    foodName: "Beef Suya with Fried Plantains",
    foodProcedure:
      "Grilled spicy beef skewers served with ripe fried plantains (dodo)",
    caloriesContained: 550,
    timeTaken: 35,
    takenAs: "Lunch",
  },
  {
    id: 6,
    foodName: "Ofada Rice with Ayamase Stew",
    foodProcedure:
      "Local brown rice served with spicy green pepper sauce and assorted meats",
    caloriesContained: 650,
    timeTaken: 45,
    takenAs: "Dinner",
  },
  {
    id: 7,
    foodName: "Moi Moi with Custard",
    foodProcedure: "Steamed bean pudding served with sweetened custard",
    caloriesContained: 400,
    timeTaken: 40,
    takenAs: "Breakfast",
  },
  {
    id: 8,
    foodName: "Pepper Soup with Semo",
    foodProcedure:
      "Spicy meat or fish broth served with semolina (semo) swallow",
    caloriesContained: 500,
    timeTaken: 35,
    takenAs: "Lunch",
  },
  {
    id: 9,
    foodName: "Efo Riro with Amala",
    foodProcedure:
      "Vegetable stew with assorted meats, served with yam flour swallow (amala)",
    caloriesContained: 580,
    timeTaken: 50,
    takenAs: "Dinner",
  },
  {
    id: 10,
    foodName: "Bread and Akamu (Corn Pap)",
    foodProcedure: "Soft bread dipped in fermented corn pudding (akamu)",
    caloriesContained: 350,
    timeTaken: 10,
    takenAs: "Breakfast",
  },
  {
    id: 11,
    foodName: "Fried Rice with Turkey",
    foodProcedure:
      "Nigerian-style fried rice with vegetables and grilled turkey",
    caloriesContained: 620,
    timeTaken: 45,
    takenAs: "Lunch",
  },
  {
    id: 12,
    foodName: "Okra Soup with Eba",
    foodProcedure: "Slimy okra soup with fish/meat, served with garri (eba)",
    caloriesContained: 550,
    timeTaken: 40,
    takenAs: "Dinner",
  },
  {
    id: 13,
    foodName: "Plantain and Beans (Gbegiri)",
    foodProcedure: "Ripe plantains served with bean stew (gbegiri)",
    caloriesContained: 480,
    timeTaken: 30,
    takenAs: "Breakfast",
  },
  {
    id: 14,
    foodName: "Nkwobi (Spicy Cow Foot)",
    foodProcedure: "Spicy cow foot delicacy served with palm wine or beer",
    caloriesContained: 650,
    timeTaken: 60,
    takenAs: "Lunch",
  },
  {
    id: 15,
    foodName: "Oha Soup with Fufu",
    foodProcedure: "Traditional Igbo soup with oha leaves, served with fufu",
    caloriesContained: 600,
    timeTaken: 55,
    takenAs: "Dinner",
  },
  {
    id: 16,
    foodName: "Puff Puff & Akara Combo",
    foodProcedure: "Deep-fried dough balls (puff puff) with bean cakes (akara)",
    caloriesContained: 420,
    timeTaken: 25,
    takenAs: "Breakfast",
  },
  {
    id: 17,
    foodName: "Banga Soup with Starch",
    foodProcedure: "Palm nut soup served with starch (usin)",
    caloriesContained: 680,
    timeTaken: 70,
    takenAs: "Lunch",
  },
  {
    id: 18,
    foodName: "Abacha (African Salad)",
    foodProcedure: "Shredded cassava with ugba, palm oil, and fish",
    caloriesContained: 500,
    timeTaken: 30,
    takenAs: "Dinner",
  },
  {
    id: 19,
    foodName: "Corn and Coconut (Eko)",
    foodProcedure: "Steamed cornmeal (eko) served with coconut",
    caloriesContained: 320,
    timeTaken: 20,
    takenAs: "Breakfast",
  },
  {
    id: 20,
    foodName: "Isi Ewu (Goat Head)",
    foodProcedure: "Spicy goat head delicacy served with palm wine",
    caloriesContained: 700,
    timeTaken: 90,
    takenAs: "Lunch",
  },
  {
    id: 21,
    foodName: "Edikang Ikong Soup",
    foodProcedure:
      "Vegetable soup with pumpkin leaves, waterleaf, and assorted meats",
    caloriesContained: 580,
    timeTaken: 60,
    takenAs: "Dinner",
  },
  {
    id: 22,
    foodName: "Agege Bread & Tea",
    foodProcedure: "Soft Agege bread with Nigerian-style tea (milky & sweet)",
    caloriesContained: 380,
    timeTaken: 10,
    takenAs: "Breakfast",
  },
  {
    id: 23,
    foodName: "Amala with Gbegiri & Ewedu",
    foodProcedure: "Yam flour swallow with bean and jute leaf soups",
    caloriesContained: 650,
    timeTaken: 50,
    takenAs: "Lunch",
  },
  {
    id: 24,
    foodName: "Fisherman Soup with Semo",
    foodProcedure: "Seafood-based spicy soup served with semolina",
    caloriesContained: 550,
    timeTaken: 45,
    takenAs: "Dinner",
  },
  {
    id: 25,
    foodName: "Yam Porridge (Asaro)",
    foodProcedure: "Yam cooked in a peppery sauce with fish or meat",
    caloriesContained: 500,
    timeTaken: 40,
    takenAs: "Breakfast",
  },
  {
    id: 26,
    foodName: "White Soup (Ofe Nsala)",
    foodProcedure: "Light pepper soup with catfish and utazi leaves",
    caloriesContained: 480,
    timeTaken: 50,
    takenAs: "Lunch",
  },
  {
    id: 27,
    foodName: "Boli (Roasted Plantain) with Fish",
    foodProcedure: "Grilled plantain served with pepper sauce and grilled fish",
    caloriesContained: 450,
    timeTaken: 30,
    takenAs: "Dinner",
  },
  {
    id: 28,
    foodName: "Coconut Rice with Chicken",
    foodProcedure: "Rice cooked in coconut milk, served with chicken",
    caloriesContained: 600,
    timeTaken: 50,
    takenAs: "Lunch",
  },
  {
    id: 29,
    foodName: "Ukwa (Breadfruit Porridge)",
    foodProcedure: "Breadfruit cooked with palm oil and spices",
    caloriesContained: 520,
    timeTaken: 60,
    takenAs: "Dinner",
  },
  {
    id: 30,
    foodName: "Tomato Stew with Boiled Rice",
    foodProcedure: "Nigerian-style tomato stew served with plain boiled rice",
    caloriesContained: 550,
    timeTaken: 40,
    takenAs: "Lunch",
  },
];

export default suggestions;
